services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:8
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
  storage:
    image: minio/minio:latest
    command: server /data --console-address :9001
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "root"
      MINIO_ROOT_PASSWORD: "rootroot"
    volumes:
      - ./bin/bucket-data:/data

  redis:
    image: redis:6.2
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgadmin_data:
