name: Build, Lint, Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  swagger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.0"
          cache: true
          cache-dependency-path: go.sum

      - name: Install and Generate Swagger
        run: |
          go install github.com/swaggo/swag/v2/cmd/swag@v2.0.0-rc4
          export PATH=$PATH:$(go env GOPATH)/bin
          swag init -v3.1 -o docs -g main.go --parseDependency --parseInternal

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.5
          args: --timeout=10m

      - name: Run Tests
        run: go test -v ./... --ldflags="-checklinkname=0"

      - name: Build
        run: go build -o bin/server --ldflags="-checklinkname=0"
