name: Deploy
on:
  push:
    branches:
      - main

jobs:
  swagger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"
          cache: true
          cache-dependency-path: go.sum
      - name: Install and Generate Swagger
        run: |
          go install github.com/swaggo/swag/v2/cmd/swag@v2.0.0-rc4
          export PATH=$PATH:$(go env GOPATH)/bin
          swag init -v3.1 -o docs -g main.go --parseDependency --parseInternal
      - name: Upload Swagger Docs
        uses: actions/upload-artifact@v4
        with:
          name: swagger-docs
          path: docs/

  lint:
    runs-on: ubuntu-latest
    needs: swagger
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Swagger Docs
        uses: actions/download-artifact@v4
        with:
          name: swagger-docs
          path: docs/
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"
          cache: true
          cache-dependency-path: go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.5
          args: --timeout=10m

  test:
    needs:
      - swagger
      - lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Swagger Docs
        uses: actions/download-artifact@v4
        with:
          name: swagger-docs
          path: docs/
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"
          cache: true
          cache-dependency-path: go.sum
      - name: Test
        run: go test -v ./...

  build:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Swagger Docs
        uses: actions/download-artifact@v4
        with:
          name: swagger-docs
          path: docs/
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.2"
          cache: true
          cache-dependency-path: go.sum
      - name: Build
        run: go build -o bin/server

  deploy:
    needs:
      - build

    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Swagger Docs
        uses: actions/download-artifact@v4
        with:
          name: swagger-docs
          path: docs/
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"
          cache: true
          cache-dependency-path: go.sum
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Convert repo name to lowercase
        run: echo "REPO_NAME=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Build and push api container
        id: docker_build_api
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ env.REPO_NAME }}:latest
          context: .
          file: ./Dockerfile
      - name: Deploy api
        uses: deploys-app/deploys-action@v1
        with:
          project: ${{ secrets.DEPLOYS_PROJECT }}
          location: gke.cluster-rcf2
          name: ${{ secrets.DEPLOYS_DEPLOY_NAME }}
          image: ghcr.io/${{ env.REPO_NAME }}@${{ steps.docker_build_api.outputs.digest }}
        env:
          DEPLOYS_AUTH_USER: ${{ secrets.DEPLOYS_AUTH_USER }}
          DEPLOYS_AUTH_PASS: ${{ secrets.DEPLOYS_AUTH_PASS }}
