name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    needs:
      - build

    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"
          cache: true
          cache-dependency-path: go.sum

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Convert repo name to lowercase
        run: echo "REPO_NAME=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push api container
        id: docker_build_api
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ env.REPO_NAME }}:latest
          context: .
          file: ./Dockerfile

      - name: Deploy api
        uses: deploys-app/deploys-action@v1
        with:
          project: ${{ secrets.DEPLOYS_PROJECT }}
          location: gke.cluster-rcf2
          name: ${{ secrets.DEPLOYS_DEPLOY_NAME }}
          image: ghcr.io/${{ env.REPO_NAME }}@${{ steps.docker_build_api.outputs.digest }}

        env:
          DEPLOYS_AUTH_USER: ${{ secrets.DEPLOYS_AUTH_USER }}
          DEPLOYS_AUTH_PASS: ${{ secrets.DEPLOYS_AUTH_PASS }}
